version: "2"

checks:
  file-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 8

plugins:
  pep8:
    enabled: true

exclude_patterns:
- "**/tests/"
- "**/migrations/"
- "**/fixtures/"