language: python
python: "3.5.2"
services:
  - postgresql
addons:
    postgresql: "9.4"

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis.git
  - cd osis
  - git submodule init
  - git submodule update
  - pip install -r travis-requirements.txt
  - rm -Rf dissertation
  - ln -s $PROJECT_DIR dissertation

before_script:
  - cp .env.example .env
  - echo 'APPS_TO_TEST += ("dissertation",)' >> backoffice/settings/local.py
  - echo >> .env
  - echo "POSTGRES_USER = 'postgres'" >> .env
  - echo "POSTGRES_PASSWORD = ''" >> .env
  - python3 manage.py compilemessages
  - psql -c 'create database osis_local;' -U postgres

script:
  - python3 manage.py compilemessages && coverage run manage.py test --exclude-tag=selenium

after_success:
 - pip install coveralls
 - coveralls
