env:
  global:
    - CC_TEST_REPORTER_ID=6a77439ce12ce968feae755e39a015a5e3597a361881c5c88d35eaf30bdceb6c
   

language: python
python: "3.5.2"
services:
  - postgresql
addons:
    postgresql: "9.4"

install:
  - export PROJECT_DIR=`pwd`
  - cd /tmp
  - git clone https://github.com/uclouvain/osis.git
  - cd osis
  - git submodule init
  - git submodule update
  - pip install -r travis-requirements.txt
  - rm -Rf dissertation
  - ln -s $PROJECT_DIR dissertation

before_script:
  - cp .env.example .env
  - echo 'APPS_TO_TEST += ("dissertation",)' >> backoffice/settings/local.py
  - echo >> .env
  - echo "POSTGRES_USER = 'postgres'" >> .env
  - echo "POSTGRES_PASSWORD = ''" >> .env
  - psql -c 'create database osis_local;' -U postgres
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > tmp/osis/cc-test-reporter"
  - "chmod +x tmp/osis/cc-test-reporter"
  - "tmp/osis/cc-test-reporter before-build"

script:
  - python3 manage.py compilemessages && coverage run manage.py test --exclude-tag=selenium

after_script:
  - "coverage xml"
  - "tmp/osis/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

