# Generated by Django 2.2.13 on 2021-05-26 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('dissertation', '0001_initial'), ('dissertation', '0002_auto_20160623_1006'), ('dissertation', '0003_dissertation_defend_periode'), ('dissertation', '0004_auto_20160628_1109'), ('dissertation', '0005_auto_20160628_1702'), ('dissertation', '0006_auto_20160711_1229'), ('dissertation', '0007_auto_20160714_1551'), ('dissertation', '0008_dissertation_defend_year'), ('dissertation', '0009_auto_20160726_1851'), ('dissertation', '0010_auto_20160816_1533'), ('dissertation', '0011_auto_20160824_1600'), ('dissertation', '0012_propositiondissertation_creator'), ('dissertation', '0013_auto_20160826_1614'), ('dissertation', '0014_auto_20160916_1457'), ('dissertation', '0015_auto_20160916_1538'), ('dissertation', '0016_auto_20160916_1639'), ('dissertation', '0017_add_adviser_uuid'), ('dissertation', '0018_populate_adviser_uuid'), ('dissertation', '0019_set_adviser_uuid_not_nullable'), ('dissertation', '0020_propositiondocumentfile'), ('dissertation', '0021_dissertationdocumentfile'), ('dissertation', '0022_add_uuid_field'), ('dissertation', '0023_populate_uuid_field'), ('dissertation', '0024_auto_20161010_1049'), ('dissertation', '0025_propositionoffer'), ('dissertation', '0026_remove_propositiondissertation_offer_proposition'), ('dissertation', '0027_auto_20161123_0918'), ('dissertation', '0028_auto_20170410_1511'), ('dissertation', '0029_auto_20170428_1702'), ('dissertation', '0030_auto_20170503_1628'), ('dissertation', '0031_auto_20170704_1335'), ('dissertation', '0032_auto_20171010_1438'), ('dissertation', '0033_auto_20180306_1634'), ('dissertation', '0034_offerproposition_global_email_to_commission'), ('dissertation', '0035_topiceducationgroup'), ('dissertation', '0036_auto_20180723_1534'), ('dissertation', '0037_offerproposition_education_group'), ('dissertation', '0038_auto_20181217_1153'), ('dissertation', '0039_auto_20181217_1442'), ('dissertation', '0040_populate_educationgroup_fields'), ('dissertation', '0041_auto_20190109_1543'), ('dissertation', '0042_auto_20190211_1136'), ('dissertation', '0043_auto_20190213_1439'), ('dissertation', '0044_auto_20190221_1325'), ('dissertation', '0045_auto_20190312_1148'), ('dissertation', '0046_auto_20190320_1038'), ('dissertation', '0047_check_if_propositions_dissertations_attached_to_offer_propossition_with_education_group__not_none'), ('dissertation', '0048_auto_20191014_2347'), ('dissertation', '0049_auto_20191108_1111'), ('dissertation', '0050_auto_20191209_1018'), ('dissertation', '0051_auto_20191211_1458'), ('dissertation', '0052_auto_20210419_1517')]

    initial = True

    dependencies = [
        ('base', '0486_message templates_postponements_order'),
        ('base', '0315_auto_20180724_0823'),
        ('osis_common', '0006_modifications_documentfile'),
        ('base', '0059_auto_20160718_1435'),
        ('osis_common', '0014_messagequeuecache'),
        ('base', '0428_auto_20190201_1520'),
        ('base', '0306_auto_20180709_1334'),
        ('base', '0054_scoresencoding'),
        ('base', '0312_educationgroupyear_languages'),
        ('base', '0058_add_initial_users_to_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRF', 'Professor'), ('MGR', 'Course manager')], default='PRF', max_length=3)),
                ('available_by_email', models.BooleanField(default=False)),
                ('available_by_phone', models.BooleanField(default=False)),
                ('available_at_office', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['person__last_name', 'person__middle_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='OfferPropositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name_short', models.CharField(max_length=10)),
                ('name_long', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=200)),
                ('student_can_manage_readers', models.BooleanField(default=True)),
                ('adviser_can_suggest_reader', models.BooleanField(default=False)),
                ('evaluation_first_year', models.BooleanField(default=False)),
                ('validation_commission_exists', models.BooleanField(default=False)),
                ('end_visibility_dissertation', models.DateField(default=django.utils.timezone.now)),
                ('end_visibility_proposition', models.DateField(default=django.utils.timezone.now)),
                ('start_visibility_dissertation', models.DateField(default=django.utils.timezone.now)),
                ('start_visibility_proposition', models.DateField(default=django.utils.timezone.now)),
                ('end_edit_title', models.DateField(default=django.utils.timezone.now)),
                ('end_jury_visibility', models.DateField(default=django.utils.timezone.now)),
                ('start_edit_title', models.DateField(default=django.utils.timezone.now)),
                ('start_jury_visibility', models.DateField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('offer_proposition_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferPropositionGroup')),
                ('global_email_to_commission', models.BooleanField(default=False)),
                ('education_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_proposition', to='base.EducationGroup')),
            ],
            options={
                'ordering': ['offer_proposition_group', 'acronym'],
            },
        ),
        migrations.CreateModel(
            name='PropositionDissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration', models.CharField(choices=[('POSSIBLE', 'Possible'), ('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden')], default='FORBIDDEN', max_length=12, verbose_name='Collaboration')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('level', models.CharField(choices=[('SPECIFIC', 'Specific subject'), ('THEME', 'Large theme')], default='DOMAIN', max_length=12, verbose_name='Subject developement level')),
                ('max_number_student', models.IntegerField(verbose_name='Indicative number of places for this subject')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('type', models.CharField(choices=[('RDL', 'Litterature review'), ('EMP', 'Empirical research'), ('THE', 'Theoretical analysis'), ('PRO', 'Project dissertation'), ('DEV', 'Development dissertation'), ('OTH', 'Other')], default='OTH', max_length=12, verbose_name='Subject type')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visibility')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Author')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DissertationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be received defended'), ('DEFENDED', 'Defended'), ('ENDED', 'End'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student', verbose_name='Author')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='dissertation.PropositionDissertation', verbose_name='Dissertation subject')),
                ('defend_periode', models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], default='UNDEFINED', max_length=12, null=True, verbose_name='Defense period')),
                ('defend_year', models.IntegerField(blank=True, null=True, verbose_name='Defense year')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dissertation.DissertationLocation', verbose_name='Dissertation location')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('education_group_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_group_years', to='base.EducationGroupYear', verbose_name='Programs')),
            ],
            options={
                'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DissertationDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osis_common.DocumentFile')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='dissertation_documents_files',
            field=models.ManyToManyField(through='dissertation.DissertationDocumentFile', to='osis_common.DocumentFile'),
        ),
        migrations.CreateModel(
            name='PropositionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferProposition')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ['offer_proposition__acronym'],
            },
        ),
        migrations.AddField(
            model_name='propositiondissertation',
            name='offer_propositions',
            field=models.ManyToManyField(related_name='offer_propositions', through='dissertation.PropositionOffer', to='dissertation.OfferProposition', verbose_name='Links to offer_propositions'),
        ),
        migrations.CreateModel(
            name='DissertationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROMOTEUR', 'Promotor'), ('CO_PROMOTEUR', 'Co-Promotor'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship Master'), ('PRESIDENT', 'President')], max_length=12)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertations_roles', to='dissertation.Adviser')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'unique_together': {('status', 'adviser', 'dissertation')},
            },
        ),
        migrations.AddField(
            model_name='adviser',
            name='dissertations',
            field=models.ManyToManyField(related_name='advisers', through='dissertation.DissertationRole', to='dissertation.Dissertation'),
        ),
        migrations.CreateModel(
            name='PropositionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
                ('status', models.CharField(choices=[('PROMOTEUR', 'Promotor'), ('CO_PROMOTEUR', 'Co-Promotor'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship Master'), ('PRESIDENT', 'President')], default='PROMOTEUR', max_length=12)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='adviser',
            name='proposition_dissertation',
            field=models.ManyToManyField(related_name='advisers', through='dissertation.PropositionRole', to='dissertation.PropositionDissertation'),
        ),
        migrations.CreateModel(
            name='FacultyAdviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Adviser')),
                ('education_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup')),
            ],
        ),
        migrations.AddField(
            model_name='adviser',
            name='education_groups',
            field=models.ManyToManyField(related_name='advisers', through='dissertation.FacultyAdviser', to='base.EducationGroup'),
        ),
        migrations.CreateModel(
            name='PropositionDocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osis_common.DocumentFile')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DissertationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be received defended'), ('DEFENDED', 'Defended'), ('ENDED', 'End'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12)),
                ('status_to', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be received defended'), ('DEFENDED', 'Defended'), ('ENDED', 'End'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True)),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DissertationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
