# Generated by Django 3.2.12 on 2022-06-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_dissertation_dissertation_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissertation',
            old_name='dissertation_document_file',
            new_name='dissertation_file',
        ),
    ]
