# Generated by Django 3.2.12 on 2022-06-29 18:14

from django.db import migrations, models
import osis_document_components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_rename_dissertation_document_file_dissertation_dissertation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondissertation',
            name='proposition_dissertation_file',
            field=osis_document_components.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=1),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='dissertation_file',
            field=osis_document_components.fields.FileField(base_field=models.UUIDField(), default=list, null=True, size=1),
        ),
    ]
