# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0311_auto_20180719_1551'),
        ('dissertation', '0034_offerproposition_global_email_to_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
    ]
