# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0035_topiceducationgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiceducationgroup',
            name='education_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='topiceducationgroup',
            name='proposition_dissertation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dissertation.PropositionDissertation'),
        ),
    ]
