# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0312_educationgroupyear_languages'),
        ('dissertation', '0035_topiceducationgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dissertations',
                to='base.EducationGroupYear'
            ),
        ),
        migrations.AddField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
    ]
