# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 07:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0315_auto_20180724_0823'),
        ('dissertation', '0036_auto_20180723_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='education_group',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='dissertations', to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='base.EducationGroup'),
        ),
    ]
