# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0315_auto_20180724_0823'),
        ('dissertation', '0036_auto_20180723_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='education_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
    ]
