# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0037_offerproposition_education_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dissertations', to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EducationGroup'),
        ),
    ]
