# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0037_offerproposition_education_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproposition',
            name='education_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Offer'),
        ),
    ]
