# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0037_offerproposition_education_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='type',
            field=models.CharField(choices=[('PRF', 'Teacher'), ('MGR', 'Manager')], default='PRF', max_length=3),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promotor'), ('DIR_OK', 'Accepted by promotor'), ('DIR_KO', 'Refused by promotor'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to 1st year evaluation'), ('EVA_OK', 'Accepted by 1st year evaluation'), ('EVA_KO', '1st year evaluation failed'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended with success'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Promotor'), ('CO_PROMOTEUR', 'Co-Promotor'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship Master'), ('PRESIDENT', 'President')], max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationupdate',
            name='status_from',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promotor'), ('DIR_OK', 'Accepted by promotor'), ('DIR_KO', 'Refused by promotor'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to 1st year evaluation'), ('EVA_OK', 'Accepted by 1st year evaluation'), ('EVA_KO', '1st year evaluation failed'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended with success'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationupdate',
            name='status_to',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promotor'), ('DIR_OK', 'Accepted by promotor'), ('DIR_KO', 'Refused by promotor'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to 1st year evaluation'), ('EVA_OK', 'Accepted by 1st year evaluation'), ('EVA_KO', '1st year evaluation failed'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended with success'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='collaboration',
            field=models.CharField(choices=[('POSSIBLE', 'Possible'), ('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden')], default='FORBIDDEN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('SPECIFIC', 'Specific subject'), ('THEME', 'Large theme')], default='DOMAIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'Litterature review'), ('EMP', 'Empirical research'), ('THE', 'Theoretical analysis'), ('PRO', 'Project dissertation'), ('DEV', 'Development dissertation'), ('OTH', 'Other')], default='OTH', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositionrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Promotor'), ('CO_PROMOTEUR', 'Co-Promotor'), ('READER', 'Reader'), ('ACCOMPANIST', 'Accompanist'), ('INTERNSHIP', 'Internship Master'), ('PRESIDENT', 'President')], default='PROMOTEUR', max_length=12),
        ),
    ]
