# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-17 14:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0038_auto_20181217_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiceducationgroup',
            name='education_group',
        ),
        migrations.RemoveField(
            model_name='topiceducationgroup',
            name='proposition_dissertation',
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='base.EducationGroupYear'),
        ),
        migrations.AlterField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='education_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
        migrations.DeleteModel(
            name='TopicEducationGroup',
        ),
    ]
