# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-11 11:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0428_auto_20190201_1520'),
        ('dissertation', '0041_auto_20190109_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='dissertations',
            field=models.ManyToManyField(related_name='advisers', through='dissertation.DissertationRole', to='dissertation.Dissertation'),
        ),
        migrations.AddField(
            model_name='adviser',
            name='education_groups',
            field=models.ManyToManyField(related_name='advisers', through='dissertation.FacultyAdviser', to='base.EducationGroup'),
        ),
        migrations.AddField(
            model_name='propositiondissertation',
            name='offer_propositions',
            field=models.ManyToManyField(related_name='offer_propositions', through='dissertation.PropositionOffer', to='dissertation.OfferProposition', verbose_name='Links to offer_propositions'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], max_length=12, null=True, verbose_name='Defense period'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defense year'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='base.EducationGroupYear', verbose_name='Programs'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.DissertationLocation', verbose_name='Dissertation location'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation', verbose_name='Dissertation subject'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
