# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0043_auto_20190213_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dissertationrole',
            unique_together=set([('status', 'adviser', 'dissertation')]),
        ),
    ]
