# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-12 11:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0044_auto_20190221_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.DissertationLocation', verbose_name='Dissertation location'),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_proposition', to='base.Offer'),
        ),
    ]
