# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-20 10:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0045_auto_20190312_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadviser',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Adviser'),
        ),
        migrations.AlterField(
            model_name='facultyadviser',
            name='education_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.EducationGroup'),
        ),
        migrations.AlterField(
            model_name='facultyadviser',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
        ),
    ]
