# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0045_auto_20190312_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyadviser',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Adviser'),
        ),
    ]
