# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0047_check_if_propositions_dissertations_attached_to_offer_propossition_with_education_group__not_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissertations', to='dissertation.PropositionDissertation', verbose_name='Dissertation subject'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='collaboration',
            field=models.CharField(choices=[('POSSIBLE', 'Possible'), ('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden')], default='FORBIDDEN', max_length=12, verbose_name='Collaboration'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('SPECIFIC', 'Specific subject'), ('THEME', 'Large theme')], default='DOMAIN', max_length=12, verbose_name='Subject developement level'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='max_number_student',
            field=models.IntegerField(verbose_name='Indicative number of places for this subject'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'Litterature review'), ('EMP', 'Empirical research'), ('THE', 'Theoretical analysis'), ('PRO', 'Project dissertation'), ('DEV', 'Development dissertation'), ('OTH', 'Other')], default='OTH', max_length=12, verbose_name='Subject type'),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Visibility'),
        ),
    ]
