# Generated by Django 2.2.5 on 2019-11-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0048_auto_20191014_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyadviser',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offerproposition',
            name='offer',
        ),
    ]
