# Generated by Django 2.2.5 on 2019-11-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0049_auto_20191108_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissertation',
            old_name='education_group_year_start',
            new_name='education_group_year',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='offer_year_start',
        ),
        migrations.AlterField(
            model_name='adviser',
            name='type',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('COURSE_MANAGER', 'Course manager')], default='PROFESSOR', max_length=3),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(choices=[('UNDEFINED', 'undefined'), ('JANUARY', 'January'), ('JUNE', 'June'), ('SEPTEMBER', 'September')], default='UNDEFINED', max_length=12, null=True, verbose_name='Defense period'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dissertation.DissertationLocation', verbose_name='Dissertation location'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dissertations', to='dissertation.PropositionDissertation', verbose_name='Dissertation subject'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Finished'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationupdate',
            name='status_from',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Finished'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='dissertationupdate',
            name='status_to',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to promoter'), ('DIR_OK', 'Accepted by promoter'), ('DIR_KO', 'Refused by promoter'), ('COM_SUBMIT', 'Submitted to commission'), ('COM_OK', 'Accepted by commission'), ('COM_KO', 'Refused by commission'), ('EVA_SUBMIT', 'Submitted to first year evaluation'), ('EVA_OK', 'Accepted by first year evaluation'), ('EVA_KO', 'Refused by first year evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Finished'), ('ENDED_WIN', 'Win'), ('ENDED_LOS', 'Reported')], default='DRAFT', max_length=12),
        ),
    ]
