# Generated by Django 2.2.5 on 2019-12-11 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0050_auto_20191209_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='education_group_years', to='base.EducationGroupYear', verbose_name='Programs'),
        ),
    ]
